OSOE-835: Add test for BlockMediaThemeTemplateDirectAccessMiddleware
Lombiq/Hosting-Media-Theme pull request #61
Opened 2024-05-10 08:38 UTC by AydinE

2024-05-14 21:24 UTC, DemeSzabolcs requested changes

2024-05-14 21:24 UTC, DemeSzabolcs commented on Lombiq.Hosting.MediaTheme.Tests.UI/Extensions/TestCaseUITestContextExtensions.cs
>  namespace Lombiq.Hosting.MediaTheme.Tests.UI.Extensions;
We are testing `BlockMediaThemeTemplateDirectAccessMiddleware.cs` here, that's inside `Lombiq.Hosting.MediaTheme.Bridge`, so we are testing that module. So instead of putting this test here, I would rather put it in a new project called `Lombiq.Hosting.MediaTheme.Bridge.Tests.UI`.

Just for example, you can see, that the other modules have the matching `Tests.UI` modules too (at least most of them, where we test something):
![image](https://github.com/Lombiq/Hosting-Media-Theme/assets/80963259/2531cf2c-aa58-4765-9480-80b848afecd2)

![image](https://github.com/Lombiq/Hosting-Media-Theme/assets/80963259/c73dd830-d3f3-4c45-a8bd-8dcfaf585bc0)

2024-05-16 14:21 UTC, AydinE commented
@DemeSzabolcs I believe I have resolved all your notes and it's ready for another review whenever you have time

2024-05-17 00:48 UTC, DemeSzabolcs requested changes

2024-05-17 00:48 UTC, DemeSzabolcs commented on .editorconfig
This file is not needed. I think it got added in your previous PRs too automatically or something. I'm not sure why though.

2024-05-17 00:48 UTC, DemeSzabolcs commented on Lombiq.Hosting.MediaTheme.Bridge.Tests.UI/Extensions/TestCaseUIBridgeTestContextExtensions.cs
You can name this just `TestCaseUITestContextExtensions.cs`, since it's already in a different module.

2024-05-17 00:49 UTC, DemeSzabolcs commented
@AydinE I reviewed it again. I found two minor things, otherwise looks good!

2024-05-17 08:40 UTC, AydinE commented
> @AydinE I reviewed it again. I found two minor things, otherwise looks good!

Should be good now, I will see if I can globally exclude the editorconfig file somehow seems like it sometimes sneaks itself in there without me noticing.

2024-05-18 18:44 UTC, merged