NEST-332: Address some leftovers for Media Theme
Lombiq/Hosting-Media-Theme pull request #7
Opened 2022-09-22 13:44 UTC by barthamark

2022-09-22 17:50 UTC, wAsnk requested changes

2022-09-22 17:50 UTC, wAsnk commented on Lombiq.Hosting.MediaTheme.Tests.UI/License.md
> +Copyright © 2021, [Lombiq Technologies Ltd.](https://lombiq.com)
```suggestion
Copyright © 2022, [Lombiq Technologies Ltd.](https://lombiq.com)
```

2022-09-22 17:50 UTC, wAsnk commented on Lombiq.Hosting.MediaTheme.Tests.UI/Lombiq.Hosting.MediaTheme.Tests.UI.csproj
> +        <Copyright>Copyright © 2021, Lombiq Technologies Ltd.</Copyright>
```suggestion
        <Copyright>Copyright © 2022, Lombiq Technologies Ltd.</Copyright>
```

2022-09-22 17:50 UTC, wAsnk commented on Lombiq.Hosting.MediaTheme.Tests.UI/Lombiq.Hosting.MediaTheme.Tests.UI.csproj
> +        <TargetFramework>net6.0</TargetFramework>
```suggestion
        <TargetFramework>net6.0</TargetFramework>
        <DefaultItemExcludes>$(DefaultItemExcludes);.git*;node_modules\**</DefaultItemExcludes>
```

2022-09-22 17:50 UTC, wAsnk commented on Lombiq.Hosting.MediaTheme/Recipes/_MediaTheme/Templates/Example.liquid
> +<img src="/mediatheme/example.png" alt="example" />
Ez az adott tenant-hoz tartozó /mediatheme/example.png képét fogja megnézni vagy a default tenantét?

2022-09-26 14:28 UTC, barthamark commented on Lombiq.Hosting.MediaTheme/Recipes/_MediaTheme/Templates/Example.liquid
> +<img src="/mediatheme/example.png" alt="example" />
Nem, de fixeltem. 😀

2022-09-26 16:28 UTC, wAsnk approved these changes

2022-09-26 16:28 UTC, merged